# # -*- coding: utf-8 -*-

# # Form implementation generated from reading ui file 'Data\update.ui'
# #
# # Created by: PyQt5 UI code generator 5.15.4
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic5 is
# # run again.  Do not edit this file unless you know what you are doing.


# from PyQt5 import QtCore, QtGui, QtWidgets


# class Ui_Form(object):
#     def setupUi(self, Form):
#         self.newadd = QtWidgets.QFrame(Form)
#         self.newadd.setFrameShape(QtWidgets.QFrame.StyledPanel)
#         self.newadd.setFrameShadow(QtWidgets.QFrame.Raised)
#         self.newadd.setObjectName("newadd")
#         self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.newadd)
#         self.verticalLayout_10.setContentsMargins(5, 0, 5, 0)
#         self.verticalLayout_10.setSpacing(5)
#         self.verticalLayout_10.setObjectName("verticalLayout")
#         self.label_10 = QtWidgets.QLabel(self.newadd)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
#         self.label_10.setSizePolicy(sizePolicy)
#         self.label_10.setAlignment(QtCore.Qt.AlignCenter)
#         self.label_10.setObjectName("label")
#         self.verticalLayout_10.addWidget(self.label_10)
#         self.frame = QtWidgets.QFrame(self.newadd)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
#         self.frame.setSizePolicy(sizePolicy)
#         self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
#         self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
#         self.frame.setObjectName("frame")
#         self.horizontalLayout_10
#      = QtWidgets.QHBoxLayout(self.frame)
#         self.horizontalLayout_10
#     .setContentsMargins(5, 0, 5, 0)
#         self.horizontalLayout_10
#     .setSpacing(3)
#         self.horizontalLayout_10
#     .setObjectName("horizontalLayout")
#         self.importLabel = QtWidgets.QLabel(self.frame)
#         self.importLabel.setObjectName("label_2")
#         self.horizontalLayout_10
#     .addWidget(self.importLabel)
#         self.toolButton = QtWidgets.QToolButton(self.frame)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
#         self.toolButton.setSizePolicy(sizePolicy)
#         self.toolButton.setAutoRaise(False)
#         self.toolButton.setObjectName("toolButton")
#         self.horizontalLayout_10
#     .addWidget(self.toolButton)
#         self.horizontalLayout_10
#     .setStretch(0, 2)
#         self.horizontalLayout_10
#     .setStretch(1, 1)
#         self.verticalLayout_10.addWidget(self.frame)
#         spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
#         self.verticalLayout_10.addItem(spacerItem)
#         self.verticalLayout_10.setStretch(1, 1)
#         self.verticalLayout_10.setStretch(2, 3)
#         self.gridLayout.addWidget(self.newadd, 0, 1, 1, 1)

#         self.retranslateUi(Form)
#         QtCore.QMetaObject.connectSlotsByName(Form)

#     def retranslateUi(self, Form):
#         _translate = QtCore.QCoreApplication.translate
#         Form.setWindowTitle(_translate("Form", "Form"))
#         self.label_10.setText(_translate("Form", "Import"))
#         self.importLabel.setText(_translate("Form", "Count Handle"))
#         self.toolButton.setText(_translate("Form", "asds"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec_())










