
from PyQt5 import QtCore, QtGui, QtWidgets
import typing
from MyPyQt5 import MyQTreeWidget , QObject


class Page1(QObject):
    def __init__(self,parent:typing.Optional[QtWidgets.QWidget]) -> None:
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(parent)
        self.verticalLayout_2.setContentsMargins(0, 3, 3, 3)
        self.verticalLayout_2.setSpacing(0)
        self.frame = QtWidgets.QFrame(parent)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.channelLabel = QtWidgets.QLabel(self.frame,text="Channel Name")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PageMainLabel = QtWidgets.QLabel(parent,text="Scraper")
        self.PageMainLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.verticalLayout_2.addWidget(self.PageMainLabel)
        self.PageMainLabel.setFont(font)
        self.channelLabel.setFont(font)
        self.channelLabel.setToolTipDuration(-1)
        self.channelLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout.addWidget(self.channelLabel)
        self.channelLineEdit = QtWidgets.QLineEdit(self.frame)
        self.channelLineEdit.setPlaceholderText("@User Name Or Channel Name")
        self.channelLineEdit.setStyleSheet("""background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(68, 90, 25, 203));color:white;border-radius:6px;""")
        self.horizontalLayout.addWidget(self.channelLineEdit)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.limitLabel = QtWidgets.QLabel(self.frame_2,text="Limit")
        self.limitLabel.setFont(font)
        self.limitLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_2.addWidget(self.limitLabel)
        self.spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox.setMinimum(10)
        self.spinBox.setMaximum(10000)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setStyleSheet("""background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(68, 90, 25, 203));color:white;border-radius:6px;""")#background-color:transparent;border:2px solid qlineargradient(spread:pad, x1:0.716, y1:0, x2:0.517, y2:0.613409, stop:0.289773 rgba(151, 133, 210, 223), stop:0.926136 rgba(0, 183, 232, 239));
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(3, 0, 3, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.start = QtWidgets.QToolButton(self.frame_3)
        self.start.setIcon(QtGui.QIcon("Data\Icons\icons8-play-96.png"))
        self.start.setIconSize(QtCore.QSize(50,50))
        self.start.setGraphicsEffect(self.shadow())
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        self.start.setSizePolicy(sizePolicy)
        self.horizontalLayout_3.addWidget(self.start)
        self.stop = QtWidgets.QToolButton(self.frame_3)
        self.stop.setIcon(QtGui.QIcon("Data\Icons\icons8-unavailable-96.png"))
        self.stop.setGraphicsEffect(self.shadow())
        self.stop.setIconSize(QtCore.QSize(50,50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        self.stop.setSizePolicy(sizePolicy)
        self.horizontalLayout_3.addWidget(self.stop)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(parent)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout.setSpacing(5)
        self.label = QtWidgets.QLabel(self.frame_4)
        self.treeWidget = MyQTreeWidget(self.frame_4,self.label)
        # self.treeWidget.setColumnWidth(0,200)
        self.treeWidget.setColumns([" Handle","Name"])
        self.treeWidget.setStyleSheet("""color:black;""")#background-color:white;
        self.verticalLayout.addWidget(self.treeWidget)
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 4)

    def shadow(self):
        shadow = QtWidgets.QGraphicsDropShadowEffect()
        shadow.setBlurRadius(20)
        shadow.setOffset(-10,10)
        shadow.setColor(QtGui.QColor("white"))
        return shadow


class Page2(QObject):
    def __init__(self,parent:typing.Optional[QtWidgets.QWidget]) -> None:
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(parent)
        self.verticalLayout_2.setContentsMargins(0, 3, 3, 3)
        self.verticalLayout_2.setSpacing(0)
        self.frame = QtWidgets.QFrame(parent)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.channelLabel = QtWidgets.QLabel(self.frame,text="Channel Name")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PageMainLabel = QtWidgets.QLabel(parent,text="Add Members")
        self.PageMainLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.verticalLayout_2.addWidget(self.PageMainLabel)

        self.PageMainLabel.setFont(font)
        self.channelLabel.setFont(font)
        self.channelLabel.setToolTipDuration(-1)
        self.channelLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout.addWidget(self.channelLabel)
        self.channelLineEdit = QtWidgets.QLineEdit(self.frame)
        self.channelLineEdit.setPlaceholderText("Channel Link example: https://t.me/example ")
        self.channelLineEdit.setStyleSheet("""background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(68, 90, 25, 203));color:white;border-radius:6px;""")
        self.horizontalLayout.addWidget(self.channelLineEdit)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.limitLabel = QtWidgets.QLabel(self.frame_2,text="Limit")
        self.limitLabel.setFont(font)
        self.limitLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_2.addWidget(self.limitLabel)
        self.spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox.setMinimum(10)
        self.spinBox.setMaximum(10000)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setStyleSheet("""background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(68, 90, 25, 203));color:white;border-radius:6px;""")#background-color:transparent;border:2px solid qlineargradient(spread:pad, x1:0.716, y1:0, x2:0.517, y2:0.613409, stop:0.289773 rgba(151, 133, 210, 223), stop:0.926136 rgba(0, 183, 232, 239));
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(3, 0, 3, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.start = QtWidgets.QToolButton(self.frame_3)
        self.start.setIcon(QtGui.QIcon("Data\Icons\icons8-play-96.png"))
        self.start.setIconSize(QtCore.QSize(50,50))
        self.start.setGraphicsEffect(self.shadow())
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        self.start.setSizePolicy(sizePolicy)
        self.horizontalLayout_3.addWidget(self.start)
        self.stop = QtWidgets.QToolButton(self.frame_3)
        self.stop.setIcon(QtGui.QIcon("Data\Icons\icons8-unavailable-96.png"))
        self.stop.setGraphicsEffect(self.shadow())
        self.stop.setIconSize(QtCore.QSize(50,50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        self.stop.setSizePolicy(sizePolicy)
        self.horizontalLayout_3.addWidget(self.stop)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(parent)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout.setSpacing(5)
        self.label = QtWidgets.QLabel(self.frame_4)
        self.treeWidget = MyQTreeWidget(self.frame_4,self.label)
        # self.treeWidget.setColumnWidth(0,200)
        self.treeWidget.setColumns(["    Handle"])
        self.treeWidget.setStyleSheet("""color:black;""")

        self.verticalLayout.addWidget(self.treeWidget)
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 4)

    def shadow(self):
        shadow = QtWidgets.QGraphicsDropShadowEffect()
        shadow.setBlurRadius(20)
        shadow.setOffset(-10,10)
        shadow.setColor(QtGui.QColor("white"))
        return shadow

    



class Page3(QObject):
    def __init__(self,parent:typing.Optional[QtWidgets.QWidget]) -> None:
        self.verticalLayout = QtWidgets.QVBoxLayout(parent)
        self.label = QtWidgets.QLabel(parent,text="Setting")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout.addWidget(self.label)
        self.frame_2 = QtWidgets.QFrame(parent)
        self.frame_2.setStyleSheet("background-color:red;")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.label_2 = QtWidgets.QLabel(self.frame_2 ,text="Current Account : User1")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.addItems(["User1"])
        self.comboBox.setStyleSheet("""background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(68, 90, 25, 203));color:white;border-radius:6px;""")
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        # self.comboBox.setSizePolicy(sizePolicy)
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(parent)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.toolButton_2 = QtWidgets.QToolButton(self.frame)
        self.toolButton_2.setText("startbtn")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        self.toolButton_2.setSizePolicy(sizePolicy)
        self.horizontalLayout.addWidget(self.toolButton_2)
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setText("stopbtn")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        self.toolButton.setSizePolicy(sizePolicy)
        self.horizontalLayout.addWidget(self.toolButton)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setStyleSheet("""background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(68, 90, 25, 203));color:white;border-radius:6px;""")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(20, 218, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 2)









# class Popups(QtWidgets.QWidget):
#     def __init__(self):
        
#         super().__init__()
#         self.resize(100,100)

#     def addUserPopUp(self,name:str):
#         self.lbl = QtWidgets.QLabel(parent= self,text= name)
#         self.lbl.setGeometry(30,30,50,50)
#         self.lineEdit = QtWidgets.QLineEdit(self)
#         self.lineEdit.setPlaceholderText("User name here")
#         self.show()
